### ISSUE TITLE
'Generate Diagrams' and 'Generate Documentation' commands generate intermediate files only

### ISSUE THREAD

**Issue by Mohammad-Aliraqi** [LogtalkDotOrg/logtalk-for-vscode#1]
Hi

When I click on 'Logtalk: Generate Diagrams' or 'Logtalk: Generate Documentation' context menu commands, I am getting the intermediate files (DOT and XML files, respectively). But I do not get the final render of these files.

Are the 'lgt2html' and 'dot' configurations in the extension 'logtalk-for-vscode' not used any more? Do I need to run them manually?

**Comment by pmoura** [comment]
Try the latest version, 0.6.0. Beware that this version changes the configuration settings. Check the `README.md` file for details. The current fix for generating diagrams and documentation in final formats is partial. There's now a pause for the generation of the intermediate files to complete before calling the conversion scripts. But this pause may not be enough for complex projects.

**Comment by pmoura** [comment]
Better solution in version 0.6.1. No longer relying on a pause but instead waiting for the generation of the diagrams/documentation intermediate files before calling the conversion scripts. Successfully tested on macOS and Windows.

**Comment by Mohammad-Aliraqi** [comment]
Hi

I have pulled the latest tag at this point v0.8.1 and fixed the configurations respectively and I confirm that "Generate Diagrams" and "Generate Documentation" commands get the final rendering. 

I think we can call it for this ticket, thank you!
