### ISSUE TITLE
"Generate Diagrams" command pollutes the root folder of the project with its files

### ISSUE THREAD

**Issue by Mohammad-Aliraqi** [LogtalkDotOrg/logtalk-for-vscode#2]
Hi

I think it would be better if we can get all outputs of the "Generate Diagrams" command to their own subfolder instead of polluting the root folder of the project with them (mixing diagrams and source code files).

I think it makes sense to have something similar to the outputs of "Generate Documentation" command where the files are stored in their dedicated subfolder "xml_docs"

Best Regards

**Comment by pmoura** [comment]
That was in my TODO list for a long time. Fixed now in the latest git version. The default output directory is now `./dot_dias`. Note that for fine control of diagrams and documentation, it's best to define a *doclet*.

**Comment by pmoura** [comment]
P.S. The extension is now available from the Marketplace.
https://marketplace.visualstudio.com/items?itemName=LogtalkDotOrg.logtalk-for-vscode&ssr=false#user-content-configuration
