### ISSUE TITLE
Trailing period annoyance

### ISSUE THREAD

**Issue by unthingable** [LogtalkDotOrg/logtalk-for-vscode#9]
Latest VSCode development build.

Deleting characters in front of the trailing period will eventually forcefully replace the period, this is not undoable. Does not occur when there is a space after the period.

![Untitled](https://github.com/LogtalkDotOrg/logtalk-for-vscode/assets/925755/b2461e69-5b8f-431a-8845-7dfc0a57a432)

Expected: the period to be left alone.

**Comment by pmoura** [comment]
Not in front of but to the left of the trailing period. If the period is left there, as soon as you delete the `m1(G)` test, the period will be immediately replaced by `m1(G).`. I.e. back to where we started.

**Comment by cl-alexk** [comment]
Right, exactly. The behavior in heritage from the original extension and is unwelcome :)

There are plenty of reasons to temporarily have a dangling period when making edits, including fatfingering it on a blank line.

**Comment by cl-alexk** [comment]
> the period will be immediately replaced by m1(G).. I.e. back to where we started

Except not always exactly where we started, that was just one particular example. A new period on an empty line will receive a replacement that is impossible to undo without deleting the line.

Another aggravating factor: this dot replacement happens in other edit buffers (not Prolog/Logtalk) whenever the extension is enabled. My current workaround is to have another workspace with Logtalk extension disabled just to do other things (e.g. editing asciidoc documents, where numbered lists start with a period).

Personally I've never had one instance of period replacement being useful, but that aside IMO the reasons above are enough justification that removing this behavior will be a significant QoL improvement.

**Comment by cl-alexk** [comment]
![Untitled](https://github.com/user-attachments/assets/9142bf6e-b9a9-465d-a665-2681f78195e5)

An example that doesn't get back to where we started:
![Untitled](https://github.com/user-attachments/assets/d91421c0-b7f5-4f09-8aaa-4da50bd9a9bb)

Curiously, it will allow backspacing over and then typing the period with no additional punishment.

**Comment by cl-alexk** [comment]
Also, because this interferes with undo it ruins undo history, because it's impossible to keep undoing beyond that point.

**Comment by cl-alexk** [comment]
Upon a closer look I see that this has a purpose, but reacting to a standalone `.` is a little radical. What if the recursive substitution happened upon, say, `...`? Could even be made configurable.

**Comment by pmoura** [comment]
Closing as the edit helper is no longer present.
